### ISSUE TITLE
Typo on line 51 in labs/09/metric_correlation.py ?

### ISSUE THREAD

**Issue by zombak79** [ufal/npfl129#119]
Hi,

there is probably a typo in https://github.com/ufal/npfl129/blob/0d25a4e8dc2c4999b3a054a9fc57444e06d0e72c/labs/09/metric_correlation.py on line 51:
```
# TODO: Append the averate of human ratings of `sentences` to `humans`.
```

shouldn't it be average?

Vojta :)

**Comment by zombak79** [comment]
And maybe just a rhetorical question ... I think it would be nicer instead of appending to lists create np arrays full of zeros of desired shapes and insert values in it. In my solution, I am constructing np arrays from lists - not sure if its efficient :)

**Comment by zombak79** [comment]
And a final note ... is it allowed to use `scipy.stats.pearsonr`? I used it, recodex is happy with it, but I just wonder if it is not cheating :)

**Comment by zombak79** [comment]
It passes also with using of `np.corrcoef`  🤓

**Comment by foxik** [comment]
Hi, I fixed the typo, thanks :)

Personally I tend to create data in lists if they are appended gradually. Yes, it would be more memory efficient (because storing data in Python structures is quite inefficient) and slightly faster (even if not much), but I usually prefer simplicity.

For fun, I created
```python
d = np.zeros([20_000_000])
for i in range(20_000_000):
    d[i] = i
```
and
```python
d = []
for i in range(20_000_000):
    d.append(i)
d = np.array(d)
```

The user-mode CPU usage is ~2.9s for the former and ~3.3s for the latter, so not a much difference; but the difference in memory is of course large, 179M vs 953M (that is complete memory usage, ~20MB is the Python runtime itself).

But anyway I am probably happy with the current template, but thanks for the suggestion :-)
