### ISSUE TITLE
Lecture 5:13 unclear universal quantifier

### ISSUE THREAD

**Issue by eleniel-mocna** [ufal/npfl129#201]
In the lecture 5, slide 13, the universal quantifiers are unclear.
I suggest one of three options
1) (∀k): 1 ≤ k ≤ K: (is syntactically the most correct but has double colon, without it is - in my opinion - not as readable)
2) (∀1 ≤ k ≤ K): (is syntactically less correct, but more than the 3)
3) ∀(1 ≤ k ≤ K): (Is probably a syntactical nonsense, but looks better than 2)

The original way it seems (and if I'm not mistaken, semantically is so) that the ∀ belongs to the 1.
(I don't know which of the options is the best, so I created an issue instead of a PR, hope it's ok.)

**Comment by foxik** [comment]
Hi,

it is definitely perfectly fine to create an issue, especially if it is not obvious what the best solution is.

Personally I am quite happy with the current notation, I do not think it can be in reality interpreted erroneously; i.e., I think the only interpretation of $\forall~ 1 \le k \le K: \pi(\boldsymbol x)_k \le 0$ is the correct one (the colon indicates where the "quantified over" ends and the predicate starts, indicating that the $\forall$ does not belong just to the $1$), and I do not find 2. or 3. better. I think the variant 1. would need to be updated to $\forall~k: 1 \le k \le K \Rightarrow \pi(\boldsymbol x)_k \le 0$ in order to be correct, which I however find less readable.

A more correct notation would probably be $\forall~ k \in \lbrace 1, 2, \ldots, K\rbrace: \pi(\boldsymbol x)_k \le 0$  (both indicating that $k$ is integer and also more syntactically correct, because the universal quantifier is usually used on a variable belonging to some set like $\mathbb N$ or $\mathbb R$, i.e., $\forall n \in \mathbb N$). However, I find it less readable, especially then on slide 15, where there are two such quantifications on a single line.

I tried looking to Concrete Mathematics and googling around, but I did not find any better solution.

Any ideas?

**Comment by eleniel-mocna** [comment]
When I need to get some reference for logic notation, I use [these slides](https://ktiml.mff.cuni.cz/~gregor/logics/VPL06.pdf#Navigation10). Where the colon operator is omitted (doesn't mean anything, can be put in for better readability).
But you're right in that 1) is not correct.
Probably my last simple idea is:
$\pi(x)_k \ge 0 \\;\\; \\;\\; \\;\\; \\;\\; \\;\\; \\;\\; \\;\\; \\;\\; \\;\\; \\;\\;      (\forall k: 1 \ge k \ge K),$
but this also isn't too elegant...

Or... Someone (I think Milan Hladík) used the notation (or something similar):
$[K] = \\{1, ..., K\\}$ and then we would have just $\forall~ k \in[K]: \pi(\boldsymbol x)_k \le 0$
but this would require a global change in the whole lecture and I'm not sure it's worth it (I haven't noticed any other place where this would increase readability, so it probably isn't).

**Comment by foxik** [comment]
I usually follow notation used in the ML papers/books (which is sometimes different to what we learn in school), so I am not used to consider Czech materials as reference; but in this case, there is no consensus that the universal quantifier should be used with a colon.

I have also seen the notation with the brackets, but it is always unclear to me whether it is zero-based/one-based and exclusive/inclusive, so I usually prefer to use more explicit notation.

After looking through a few books it seems that the universal quantifier is not used much at all, so I tried replacing it with a textual "for" -- see https://ufal.mff.cuni.cz/~straka/courses/npfl129/2223/slides/?05#46 and https://ufal.mff.cuni.cz/~straka/courses/npfl129/2223/slides/?05#49.

Do you think it is better?

**Comment by eleniel-mocna** [comment]
Hmm... My comment didn't get sent for some reason.
This looks clearer to me and makes sense.
