### ISSUE TITLE
Text overflows outside the slide (lecture 6)

### ISSUE THREAD

**Issue by Katterrina** [ufal/npfl129#59]
https://ufal.mff.cuni.cz/~straka/courses/npfl129/2021/slides/?06#19 last row overflows

**Comment by foxik** [comment]
I tried it in Firefox, Chromium and also in the PDF slides (https://ufal.mff.cuni.cz/~straka/courses/npfl129/2021/slides.pdf/npfl129-06.pdf , slide 7), but I cannot replicate it. But the slides are generated in the browser, so it can be caused by different OS, fonts, DPI, ...

Does it happen a lot (i.e., there are several slides which overflow for you), or is this a special case?

**Comment by Katterrina** [comment]
It works after reformulation.
